Privatise docsrs cfg flag
Fixes a docs.rs build failure by following the same approach used in
rustls, removing `doc_auto_cfg` and privatizing the docsrs cfg flag.

```
[INFO] [stderr]  Documenting instant-acme v0.8.3 (/opt/rustwide/workdir)
[INFO] [stderr] error[E0557]: feature has been removed
[INFO] [stderr]  --> src/lib.rs:5:38
[INFO] [stderr]   |
[INFO] [stderr] 5 | #![cfg_attr(docsrs, feature(doc_cfg, doc_auto_cfg))]
[INFO] [stderr]   |                                      ^^^^^^^^^^^^ feature has been removed
[INFO] [stderr]   |
[INFO] [stderr]   = note: removed in CURRENT_RUSTC_VERSION; see <https://github.com/rust-lang/rust/pull/138907> for more information
[INFO] [stderr]   = note: merged into `doc_cfg`
[INFO] [stderr]
[INFO] [stderr] error: Compilation failed, aborting rustdoc
```